# Generated by Django 3.0.2 on 2020-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_stmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=255)),
                ('member_work', models.CharField(max_length=255)),
                ('member_email', models.CharField(max_length=120)),
                ('member_phone', models.CharField(max_length=20)),
                ('member_content', models.TextField()),
                ('member_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
