# Generated by Django 3.0.2 on 2020-01-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_teammember_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='slug',
            new_name='member_slug',
        ),
    ]
