# Generated by Django 3.0.2 on 2020-01-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200110_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='member_slug',
        ),
    ]
